---
- name: STOP EC2 Instance to Save Costs (IMPORTANT!)
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    instance_name: "DevOps-Project-EC2"

  tasks:
    - name: Gather instance facts by Tag
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Name": "{{ instance_name }}"
          instance-state-name: running
      register: ec2_info
      # The ec2_instance_info module is part of the amazon.aws collection

    - name: Stop the EC2 Instance
      amazon.aws.ec2_instance:
        instance_ids: "{{ ec2_info.instances | map(attribute='instance_id') | list }}"
        region: "{{ AWS_REGION }}"
        state: stopped # This stops the instance instead of terminating it
      when: ec2_info.instances | length > 0