---
- name: Provision EC2 Instance and EBS Volume
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    instance_name: "DevOps-Project-EC2"
    keypair_name: "ssh-pair" # Must exist in your AWS account
    image_id: "ami-053b01d368b75e13d" # Example Amazon Linux 2 AMI ID (adjust for your region)

  tasks:
    - name: Launch Free Tier EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        image_id: "{{ image_id }}"
        instance_type: t2.micro # Free Tier eligible
        key_name: "{{ keypair_name }}"
        region: "{{ AWS_REGION }}"
        vpc_subnet_id: "subnet-0b3824c4e53a6e54a" # **REPLACE with a valid Subnet ID**
        security_group: "sg-092d00c34a9eafcf4" # **REPLACE with a valid Security Group ID**
        tags:
          Name: "{{ instance_name }}"
          Environment: Devops_Study
        wait: true
        state: present
      register: ec2_info

    - name: Create EBS Volume
      amazon.aws.ec2_vol:
        region: "{{ AWS_REGION }}"
        volume_size: 8 # Free Tier eligible (up to 30GB total)
        volume_type: gp2
        name: "DevOps-Project-EBS"
        tags:
          Name: DevOps-Project-EBS
        state: present
      register: ebs_volume

    - name: Attach EBS Volume to EC2 Instance
      amazon.aws.ec2_vol:
        region: "{{ AWS_REGION }}"
        instance: "{{ ec2_info.instance_ids[0] }}"
        id: "{{ ebs_volume.volume_id }}"
        device_name: /dev/sdh
        state: present